platform :ios, '15.0'

target 'UseSenseExample' do
  use_frameworks!

  # Use the local pod for development
  pod 'UseSenseSDK', :path => '../'
end

# Google's MediaPipeTasks{Common,Vision}.xcframeworks ship with a broken
# Info.plist: LibraryPath is declared as "*.a", but the actual file on disk is
# a "*.framework/" directory that contains a Mach-O ar archive. CocoaPods trusts
# the Info.plist and classifies the xcframework as a static_library, which
# makes it emit `-lMediaPipeTasksCommon` linker flags that fail to resolve
# because there is no `.a` file on disk. Patch the Info.plist in place before
# the CocoaPods analyzer reads it -- pre_install runs after pods are downloaded
# but before validate_targets and project generation.
pre_install do |installer|
  %w[MediaPipeTasksCommon MediaPipeTasksVision].each do |name|
    plist_path = "#{installer.sandbox.root}/#{name}/frameworks/#{name}.xcframework/Info.plist"
    next unless File.exist?(plist_path)

    contents = File.read(plist_path)
    fixed = contents.gsub(
      "<string>#{name}.a</string>",
      "<string>#{name}.framework</string>",
    )
    next if fixed == contents

    File.write(plist_path, fixed)
    puts "[UseSenseSDK] Patched #{plist_path} (LibraryPath .a -> .framework)"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
